ALTER TABLE public.vendas ADD COLUMN IF NOT EXISTS enviado_para_projetos BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.obras  ADD COLUMN IF NOT EXISTS venda_id UUID REFERENCES public.vendas(id) ON DELETE SET NULL;
